services:
  postgres:
    container_name: postgres
    image: "postgres:16-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./healthcheck.sh:/healthcheck.sh
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck.sh"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

volumes:
  db-data:
    driver: local
